'use client';

import React, { useState } from 'react';
import styles from './features.module.css';

interface AuditLog {
  timestamp: string;
  actor: string;
  action: string;
  result: string;
  reason: string;
  hash: string;
}

export function AuditExportButton() {
  const [loading, setLoading] = useState(false);

  const handleExport = async () => {
    try {
      setLoading(true);
      const res = await fetch('/api/audit-logs?limit=100');
      if (!res.ok) throw new Error('Failed to fetch audit logs');
      
      const logs: AuditLog[] = await res.json();
      const timestamp = new Date().toISOString();
      
      const htmlContent = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>CommerceOS Audit Report</title>
          <style>
            body { font-family: system-ui, -apple-system, sans-serif; padding: 20px; color: #333; max-width: 1200px; margin: 0 auto; }
            h1 { color: #0f172a; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px; }
            th, td { padding: 12px; border: 1px solid #e2e8f0; text-align: left; }
            th { background-color: #f8fafc; font-weight: 600; color: #475569; }
            tr:nth-child(even) { background-color: #f8fafc; }
            .footer { margin-top: 40px; font-size: 12px; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 20px; }
            code { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; font-size: 12px; background: #f1f5f9; padding: 2px 6px; border-radius: 4px; color: #0f172a; }
          </style>
        </head>
        <body>
          <h1>CommerceOS Audit Report</h1>
          <p style="color: #64748b;">Generated at: ${timestamp}</p>
          <table>
            <thead>
              <tr>
                <th>Time</th>
                <th>Actor</th>
                <th>Action</th>
                <th>Result</th>
                <th>Reason</th>
                <th>SHA-256</th>
              </tr>
            </thead>
            <tbody>
              ${logs.map(log => `
                <tr>
                  <td>${new Date(log.timestamp).toLocaleString()}</td>
                  <td>${log.actor}</td>
                  <td>${log.action}</td>
                  <td>${log.result}</td>
                  <td>${log.reason}</td>
                  <td><code>${log.hash}</code></td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="footer">Generated by CommerceOS — Tamper-Evident Audit Trail</div>
        </body>
        </html>
      `;

      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `audit-report-${timestamp.replace(/[:.]/g, '-')}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Export failed:', error);
      alert('Failed to export audit report.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <button 
      className={styles.exportBtn} 
      onClick={handleExport} 
      disabled={loading}
      aria-label="Export audit trail as HTML report"
    >
      {loading ? 'Exporting...' : 'Export Audit Report'}
    </button>
  );
}
